# Generated by Django 4.1.7 on 2023-03-21 09:39

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('buyer_name', models.CharField(default=None, max_length=20, null=True)),
                ('buyers_user_name', models.CharField(default=None, max_length=20, null=True)),
                ('buyers_password', models.CharField(default=None, max_length=20, null=True)),
                ('buyers_email', models.EmailField(max_length=30, null=True)),
                ('buyers_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('buyers_address_line1', models.CharField(default=None, max_length=20, null=True)),
                ('buyers_address_line2', models.CharField(default=None, max_length=20, null=True)),
                ('buyers_image', models.ImageField(null=True, upload_to='buyres/photos/%Y/%m/%d')),
                ('buyers_state', models.CharField(default=None, max_length=20, null=True)),
                ('buyers_district', models.CharField(default=None, max_length=20, null=True)),
                ('buyers_city', models.CharField(default=None, max_length=20, null=True)),
                ('buyers_pin_code', models.IntegerField(null=True)),
                ('buyers_status', models.BooleanField(default=True)),
                ('byures_adharcard_front_image', models.ImageField(null=True, upload_to='adhar/photos/%Y/%m/%d')),
                ('buyers_adharcard_back_image', models.ImageField(null=True, upload_to='adhar/photos/%Y/%m/%d')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
