# Generated by Django 4.1.7 on 2023-03-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyersApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyers',
            name='buyers_counter',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
