# Generated by Django 4.1.7 on 2023-03-21 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brandApp', '0001_initial'),
        ('subcategoryApp', '0001_initial'),
        ('categoryApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('product_name', models.CharField(default=None, max_length=20, null=True)),
                ('product_description', models.CharField(default=None, max_length=20, null=True)),
                ('product_quantity', models.IntegerField()),
                ('product_mrp', models.IntegerField()),
                ('product_front_image', models.ImageField(null=True, upload_to='product/photos/%Y/%m/%d')),
                ('product_back_image', models.ImageField(null=True, upload_to='product/photos/%Y/%m/%d')),
                ('product_brand', models.ManyToManyField(related_name='product_brand', to='brandApp.brand')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='categoryApp.category')),
                ('product_subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_subcategory', to='subcategoryApp.subcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
