# Generated by Django 4.1.7 on 2023-03-21 09:39

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('seller_name', models.CharField(default=None, max_length=20, null=True)),
                ('seller_user_name', models.CharField(default=None, max_length=20, null=True)),
                ('seller_password', models.CharField(default=None, max_length=20, null=True)),
                ('seller_email', models.EmailField(max_length=30, null=True)),
                ('seller_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('seller_address_line1', models.CharField(default=None, max_length=20, null=True)),
                ('seller_address_line2', models.CharField(default=None, max_length=20, null=True)),
                ('seller_image', models.ImageField(null=True, upload_to='seller/photos/%Y/%m/%d')),
                ('seller_state', models.CharField(default=None, max_length=20, null=True)),
                ('seller_district', models.CharField(default=None, max_length=20, null=True)),
                ('seller_city', models.CharField(default=None, max_length=20, null=True)),
                ('seller_pin_code', models.IntegerField(null=True)),
                ('seller_status', models.BooleanField(default=True)),
                ('seller_adharcard_front_image', models.ImageField(null=True, upload_to='adhar/photos/%Y/%m/%d')),
                ('seller_adharcard_back_image', models.ImageField(null=True, upload_to='adhar/photos/%Y/%m/%d')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
